include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/License-Scanning.gitlab-ci.yml

stages:
  - pre-build
  - test
  - publish
  - container_scanning

# Only start pipelines on Merge Requests or the default branch
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_IID
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

default:
  services: []
  tags:
    - oss
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
  interruptible: true

# Use SHA of .gitlab-ci.yml and package-lock.json for cache key
.cache-template: &cache-template
  paths:
    - node_modules/
  key:
    files:
      - .gitlab-ci.yml
      - package-lock.json
    prefix: node_modules

.node:
  image: node:16-alpine
  before_script:
    - npm install --legacy-peer-deps
  cache:
    <<: *cache-template
    policy: pull

#################################
##            RULES            ##
#################################

.on_tag_events:
  rules:
    - if: '$CI_COMMIT_TAG'

.on_default_branch_and_merge_train:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"

.on_default_branch:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

.on_default_branch_manual:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

#################################
##            BUILD            ##
#################################

populate_npm_cache:
  extends: .node
  stage: pre-build
  script:
    - echo "successfully installed dependencies"
  cache:
    <<: *cache-template
    policy: push
  rules:
    - changes:
        - .gitlab-ci.yml
        - package-lock.json
      when: always
    - when: never

lint:
  extends: .node
  stage: test
  script:
    - npm run lint

package:
  extends: .node
  stage: test
  variables:
    KUBERNETES_MEMORY_REQUEST: 2Gi
    KUBERNETES_MEMORY_LIMIT: 4Gi
  script:
    - npm run build
  artifacts:
    paths:
      - build/

publish ui docker:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  tags:
    - oss
    - docker
  dependencies:
    - package
  before_script:
    - apk add git
  script:
    - |
      echo "This is a tagged commit so major, major.minor and full tags will be pushed to registry"

      # Version is based on semantic versioning
      full_version=$(docker run --rm -v "$(pwd)":/git-semver mdomke/git-semver | grep -Eo '[0-9\.].*$')
      major_version=$(docker run --rm -v "$(pwd)":/git-semver mdomke/git-semver -format x | grep -Eo '[0-9\.].*$')
      major_minor_version=$(docker run --rm -v "$(pwd)":/git-semver mdomke/git-semver -format x.y | grep -Eo '[0-9\.].*$')

      docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

      echo "Building tharsis-ui image"
      docker build -t $CI_PROJECT_NAME:latest --no-cache .

      registry_uri="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

      echo "Version tagging the ui image"
      docker image tag $CI_PROJECT_NAME:latest $registry_uri:$full_version
      docker image tag $CI_PROJECT_NAME:latest $registry_uri:$major_version
      docker image tag $CI_PROJECT_NAME:latest $registry_uri:$major_minor_version

      echo "Pushing tharsis-ui versioned images to registry"
      docker image push $registry_uri:$full_version
      docker image push $registry_uri:$major_version
      docker image push $registry_uri:$major_minor_version

      latest_version=$(git tag | tr - \~ | sort -rV | tr \~ - | head -n1)
      if [[ "$CI_COMMIT_TAG" == "$latest_version" ]]
        then
          echo "Build is latest, tagging and pushing image as latest"
          docker image tag $CI_PROJECT_NAME:latest $registry_uri:latest
          docker image push $registry_uri:latest
      fi
  rules:
    - !reference [.on_tag_events, rules]
  interruptible: false

#################################
##            SAST             ##
#################################

container_scanning:
  stage: container_scanning
  variables:
    CS_IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest"
    GIT_STRATEGY: fetch
  rules:
    - !reference [.on_tag_events, rules]

gemnasium-dependency_scanning:
  script:
    - /analyzer run
    - cat gl-dependency-scanning-report.json
  artifacts:
    paths:
      - "**/gl-sbom-*.cdx.json"
      - gl-dependency-scanning-report.json
    reports:
      cyclonedx: "**/gl-sbom-*.cdx.json"
      dependency_scanning: gl-dependency-scanning-report.json
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

nodejs-scan-sast:
  artifacts:
    paths:
      - gl-sast-report.json
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

semgrep-sast:
  artifacts:
    paths:
      - gl-sast-report.json
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

kics-iac-sast:
  artifacts:
    paths:
      - gl-sast-report.json
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

secret_detection:
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

code_quality:
  artifacts:
    paths:
      - gl-code-quality-report.json
  tags:
    - oss
    - docker
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]

license_scanning:
  artifacts:
    reports:
      license_scanning: gl-license-scanning-report.json
    paths: [gl-license-scanning-report.json]
  rules:
    - !reference [.on_default_branch_and_merge_train, rules]
