[semgrep]

  # Object Injection Detection is way too noisy to show as a vuln in security reports. See https://github.com/eslint-community/eslint-plugin-security/issues/21#issuecomment-1157887653

  [[semgrep.ruleset]]
    disable = true
    [semgrep.ruleset.identifier]
        "type" = "semgrep_id"
        "value" = "eslint.detect-object-injection"
[kics]
  [[kics.ruleset]]
    disable = true
    [kics.ruleset.identifier]
      type = "kics_id"
      # Version pinning can break builds
      value = "d3499f6d-1651-41bb-a9a7-de925fea487b"
